# -*- coding: utf-8 -*-
"""eda_pwd01-07-04-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVtm-a8RG-HlEPxj2pP8XTjg0yBJHnL7

# Exploratory data science in Python

*Day one of the **workshop***

* What will we do?

Math?

$$
y = mx +c
$$

* Load a file?

Load library files:

**import** or **from** to **as** for customization

If unavailable: **!pip** or **install** - install
"""

from google.colab import files

"""* All python functions need prepending **Library_name.Function_name**

"""

muploea = files.upload()

import pandas as pd

import numpy as np

df = pd.read_csv('Morphological_yield_components.csv', sep=',')

df.head()

df.describe()

df.info()

df.isnull().sum()

"""# Start the exploration


"""

pip install ydata_profiling

from ydata_profiling import ProfileReport as pr

profile = pr(df, title ="EDA_Report", explorative =True)

profile.to_notebook_iframe()

